### ISSUE TITLE
synchronize local sqlite db with firebase db

### ISSUE THREAD

**Issue by shruity** [adhishlal/Firebase-Database-Android#1]
In my app I have SQLite database. I want to introduce sync between devices of my users.
I want to combine my local SQLite db with cloud Firebase db.

I want my sqlite database to be stored on firebase database when the users are logged in otherwise let it store offline. Any changes to the local database should be reflected on firebase database when logged in. Also if user deletes the local database he/she can retrieve it from firebase database. I just want to use firebase for the synchronization between local database and firebase database.

But i have no clue how to do it. Can anyone please help me with this?

**Comment by adhishlal** [comment]
Sure. Please connect with me on adhish@adhishlal.com

**Comment by vinaychandra1** [comment]
I want to add username, email and password for the Signin how do I do that using android firebase. and how to integrate the firebase and sqlite database

**Comment by shruity** [comment]
You can go through the link below:
https://www.androidhive.info/2016/10/android-working-with-firebase-realtime-database/
